---
title: "Drawing beautiful maps programmatically with R, sf and ggplot2 - Part 2: Layers"
author: "BCN, based on Mel Moreno and Mathieu Basille https://r-spatial.org/r/2018/10/25/ggplot2-sf-2.html"
output:
  html_document:
    fig_caption: no
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: '2'
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(
    message = FALSE,
    warning = FALSE,
    cache = TRUE,
    tidy = FALSE,
    fig.width = 7,
    fig.height = 7,
    out.width = "65%")

## This is just to "pre-load" all packages, and prevent the startup
## messages to show

library("ggplot2")
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("ggspatial")
library("maps")
library("tools")
library("googleway")
library("ggrepel")

library("rnaturalearth")
library("rnaturalearthdata")

library("readxl")
library("dplyr")

```

```{r further_options, include = FALSE}

install.packages(c("cowplot", "googleway", "ggplot2", "ggrepel",  "dplyr", 
    "ggspatial", "lwgeom", "rnaturalearth", "sf", "rnaturalearthdata", "viridis", "maps","tidyverse"))

```

```{r further_options2, include = FALSE}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("rnaturalearth")
library("rnaturalearthdata")
library("rnaturalearthdata")

library(readxl)
library(viridis)
library(dplyr)    # To assist with cleaning and organizing data
library(tidyverse)  
library(maps)  
library(tools)  


```

```{r SetupData}

# Get World Map Data ---------------------------------------------------

world <- ne_countries(scale = "medium", returnclass = "sf")

# target_crs <- "+proj=gall"

target_crs <- 4326

# Read and Join Swiss Missions Data --------------------------------------------

# Read Swiss Missions Data and Filter Them

SwissAsianMissionsData <- read_excel("SwissMissionsInAsiaData-2024-06-06-c.xlsx", na = "NA") %>%
  filter(APacRegion == "VRAI")  %>%
  filter(iso_a3_eh == Pays_Ambassade)

MapCountriesWithSwissEmbassy <- world %>%
  select(geometry, name, "iso_a3_eh") %>%
  left_join(SwissAsianMissionsData, by = "iso_a3_eh") %>%
  filter(APacRegion != "TRUE")

# Read city coordinates

CityDB <- read_excel("worldcities-2024-06-06.xlsx") %>%
  select(city_ascii,'iso_a3_eh', 'lat', 'lng') %>%
  mutate()

# corriger les différences de dénomination

CityDB$city_ascii <- str_replace(CityDB$city_ascii, "Rangoon", "Yangon")

CityDB$ISO_country <- CityDB$iso_a3_eh

# Create a SwissAsianMissionsLocations by selecting the city  ------------------
# from SwissAsianMissionsData and joining the dataset with the cityDB

# Create a Subset of the SwissAsianMissionsData with the locations

SwissAsianMissionsCities <- SwissAsianMissionsData %>%
  select('city_ascii', 'iso_a3_eh', 'APacRegion', 'Pays_Ambassade') %>%
  filter(city_ascii != "NA") 

# Join data sets

SwissAsianMissionsLocations <- CityDB %>%
  select('city_ascii', 'ISO_country', 'lat', 'lng') %>%
  right_join(SwissAsianMissionsCities, by = 'city_ascii') %>%
  filter(ISO_country == iso_a3_eh)

# Cordinates for the city
SwissAsianMissionsLocationsGeo <- st_as_sf(SwissAsianMissionsLocations, 
    coords = c("lng", "lat"), remove = FALSE,
    crs = target_crs, agr = "constant")

```

## Swiss embassies

```{r layers-final-plot0 fig.width = 15, out.width = "75%"}
library("ggrepel")

## ----Create bounding box-------------------------
# Choose manually the region to plot with Open Street Map
# https://www.openstreetmap.org/export
window_coord <- st_sfc(
  st_point(c(60, -10)), #left, bottom
  st_point(c(149, 55)), #right, top
  crs = target_crs #the EPSG identifier of WGS84 (used in GPS)
)

window_coord_sf <- window_coord %>%
  st_transform(crs = target_crs) %>%
  st_coordinates() # retrieve coordinates


cols <- c("none" = "grey", "TRUE" = "darkblue", "FALSE" = "lightblue")
world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = MapCountriesWithSwissEmbassy, aes(fill = APacRegion), color="white") +
  geom_sf(data = SwissAsianMissionsLocationsGeo, color="Black") +
#  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
#      aes(x = lng, y = lat, label = city_ascii), 
#       fontface = "italic", nudge_x = c(1, -1.5, 2, 2, -1), nudge_y = c(0.25, 
#        -0.25, 0.5, 0.5, -0.5)) +
  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "italic", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = "Asia Pacific",
       subtitle = "Swiss Representations",
       x = NULL, y = NULL,
       caption = "BCN")

```

## Swiss accreditations without missions


```{r SetupData2}

# Read and Join Swiss Missions Data --------------------------------------------

# Read Swiss Missions Data and Filter Them

SwissAsianMissionsData <- read_excel("SwissMissionsInAsiaData-2024-06-06-c.xlsx", na = "NA") %>%
filter(APacRegion == "VRAI") 

SwissAsianEmbassies <- SwissAsianMissionsData %>%
  filter(iso_a3_eh == Pays_Ambassade)

SwissDAInAPac <- SwissAsianMissionsData %>%
  filter(AD_accrédité == "VRAI")

SwissAsianRepresentations <- SwissAsianMissionsData

MapCountriesWithSwissEmbassy <- world %>%
  select(geometry, name, "iso_a3_eh") %>%
  left_join(SwissAsianEmbassies, by = "iso_a3_eh") %>%
  filter(APacRegion != "TRUE")

MapCountriesWithSwissRepresentation <- world %>%
  select(geometry, name, "iso_a3_eh") %>%
  left_join(SwissAsianRepresentations, by = "iso_a3_eh") %>%
  filter(APacRegion != "TRUE")

MapCountriesWithSwissDA <- world %>%
  select(geometry, name, "iso_a3_eh") %>%
  left_join(SwissAsianRepresentations, by = "iso_a3_eh") %>%
  filter(APacRegion != "TRUE")

# Read city coordinates

CityDB <- read_excel("worldcities-2024-06-06.xlsx") %>%
  select(city_ascii,'iso_a3_eh', 'lat', 'lng') %>%
  mutate()

# corriger les différences de dénomination

CityDB$city_ascii <- str_replace(CityDB$city_ascii, "Rangoon", "Yangon")

CityDB$ISO_country <- CityDB$iso_a3_eh

# Create a SwissAsianMissionsLocations by selecting the city  ------------------
# from SwissAsianMissionsData and joining the dataset with the cityDB

# Create a Subset of the SwissAsianMissionsData with the locations

SwissAsianDACities <- SwissAsianMissionsData %>%
  select('city_ascii', 'iso_a3_eh', 'APacRegion', 'Pays_Ambassade', 'AD_origine', 'AD_inland') %>%
  filter(city_ascii != "NA")  %>%
  filter(AD_inland == "VRAI") 


# Join data sets

SwissAsianMissionsLocations <- CityDB %>%
  select('city_ascii', 'ISO_country', 'lat', 'lng') %>%
  right_join(SwissAsianMissionsCities, by = 'city_ascii') %>%
  filter(ISO_country == iso_a3_eh)


SwissAsianDALocations <- CityDB %>%
  select('city_ascii', 'ISO_country', 'lat', 'lng') %>%
  right_join(SwissAsianDACities, by = 'city_ascii') %>%
  filter(ISO_country == iso_a3_eh)


# Cordinates for the city ------------------------------------------------------$
# Missions Locations
SwissAsianMissionsLocationsGeo <- st_as_sf(SwissAsianMissionsLocations, 
    coords = c("lng", "lat"), remove = FALSE,
    crs = target_crs, agr = "constant")

# DA Locations
SwissAsianDALocationsGeo <- st_as_sf(SwissAsianDALocations, 
    coords = c("lng", "lat"), remove = FALSE,
    crs = target_crs, agr = "constant")
```

```{r layers-final-plot1 fig.width = 15, out.width = "75%"}

library("ggrepel")

## ----Create bounding box-------------------------
# Choose manually the region to plot with Open Street Map
# https://www.openstreetmap.org/export
window_coord <- st_sfc(
  st_point(c(60, -10)), #left, bottom
  st_point(c(149, 55)), #right, top
  crs = target_crs #the EPSG identifier of WGS84 (used in GPS)
)

window_coord_sf <- window_coord %>%
  st_transform(crs = target_crs) %>%
  st_coordinates() # retrieve coordinates

# Missions Locations -----------------------------------------------------------

cols <- c("none" = "grey", "TRUE" = "darkblue", "FALSE" = "lightblue")
world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = MapCountriesWithSwissEmbassy, aes(fill = APacRegion), color="white") +
  geom_sf(data = SwissAsianMissionsLocationsGeo, color="Black") +
#  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
#      aes(x = lng, y = lat, label = city_ascii), 
#       fontface = "italic", nudge_x = c(1, -1.5, 2, 2, -1), nudge_y = c(0.25, 
#        -0.25, 0.5, 0.5, -0.5)) +
  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "italic", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = "Asia Pacific",
       subtitle = "Swiss Representations",
       x = NULL, y = NULL,
       caption = "BCN")

# Diplomatic accreditations ----------------------------------------------------

cols <- c("none" = "grey", "TRUE" = "darkblue", "FALSE" = "lightblue")
world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = MapCountriesWithSwissRepresentation, aes(fill = Pays_Ambassade), color="white") +
  geom_sf(data = SwissAsianMissionsLocationsGeo, color="Black") +
#  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
#      aes(x = lng, y = lat, label = city_ascii), 
#       fontface = "italic", nudge_x = c(1, -1.5, 2, 2, -1), nudge_y = c(0.25, 
#        -0.25, 0.5, 0.5, -0.5)) +
  geom_text_repel(data = SwissAsianMissionsLocationsGeo, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "italic", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = "Asia Pacific",
       subtitle = "Swiss Representations and Accreditated States",
       x = NULL, y = NULL,
       caption = "BCN")

# DA accreditations ------------------------------------------------------------

MapCountriesWithSwissDA <- cbind(MapCountriesWithSwissDA, st_coordinates(st_centroid(MapCountriesWithSwissDA)))

cols <- c("none" = "grey", "TRUE" = "darkblue", "FALSE" = "lightblue")



world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = MapCountriesWithSwissDA, aes(fill = AD_origine), color ="white") +
  # geom_label(data = MapCountriesWithSwissDA, aes(X, Y, label = ID), size = 5, fontface = "bold", 
  #      nudge_y = MapCountriesWithSwissDA$nudge_y) +
  geom_text(data = MapCountriesWithSwissDA, aes(X, Y, label = name.x), size = 2, fontface = "italic") +
  geom_sf(data = SwissAsianDALocationsGeo, shape=18, color="Black", size = 2, fontface = "bold",) +
  geom_label_repel(data = SwissAsianDALocationsGeo, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "plain", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = "Asia Pacific",
       subtitle = "Swiss DA and Accreditated States",
       x = NULL, y = NULL,
       caption = "BCN")

DisplayMap <- function(world, target_crs, window_coord_sf, StatesGeometry, CitiesGeometry, FillClass, MapTitle, MapSubtitle, MapCaption ) {
DisplayMapReturnValue <- world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = StatesGeometry, aes(fill = FillClass), color ="white") +
  # geom_label(data = MapCountriesWithSwissDA, aes(X, Y, label = ID), size = 5, fontface = "bold", 
  #      nudge_y = MapCountriesWithSwissDA$nudge_y) +
  geom_text(data = StatesGeometry, aes(X, Y, label = name.x), size = 2, fontface = "italic") +
  geom_sf(data = CitiesGeometry, shape=18, color="Black", size = 2, fontface = "bold",) +
  geom_label_repel(data = CitiesGeometry, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "plain", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = MapTitle,
       subtitle = MapSubtitle,
       x = NULL, y = NULL,
       caption = MapCaption)
  
  
    return(DisplayMapReturnValue)
}

Value <- DisplayMap (world, target_crs, window_coord_sf, MapCountriesWithSwissDA, SwissAsianDALocationsGeo, APac_Region. "Asia Pacific", "Swiss DA and Accreditated States", "BCN" )

Value

```

```{r layers-final-plot2 fig.width = 15, out.width = "75%"}

library("ggrepel")

# Déclaration de la procédure --------------------------------------------------
# DisplayMap

DisplayMap <- function(world, target_crs, window_coord_sf, StatesGeometry, CitiesGeometry, FillClass, MapTitle, MapSubtitle, MapCaption ) {

StatesGeometry <- cbind(StatesGeometry, st_coordinates(st_centroid(StatesGeometry)))

DisplayMapReturnValue <- world %>%
  filter(admin != "Antarctica") %>%
  st_transform(crs = target_crs) %>%
  ggplot() +
  geom_sf(color = "white") +
  geom_sf(data = StatesGeometry, aes(fill = FillClass), color ="white") +
  geom_text(data = StatesGeometry, aes(X, Y, label = name.x), size = 2, fontface = "italic") +
  geom_sf(data = CitiesGeometry, shape=18, color="Black", size = 2, fontface = "bold",) +
  geom_label_repel(data = CitiesGeometry, size=2,
      aes(x = lng, y = lat, label = city_ascii), 
       fontface = "plain", nudge_x = 3, nudge_y = 3) +
  coord_sf(
  xlim = window_coord_sf[, "X"],
  ylim = window_coord_sf[, "Y"],
  expand = FALSE,
  datum=NA
  ) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold"),
        axis.text.x = element_blank()) +
  labs(title = MapTitle,
       subtitle = MapSubtitle,
       x = NULL, y = NULL,
       caption = MapCaption)
  
  
    return(DisplayMapReturnValue)
}

## ----Create bounding box-------------------------
# Choose manually the region to plot with Open Street Map
# https://www.openstreetmap.org/export
window_coord <- st_sfc(
  st_point(c(60, -10)), #left, bottom
  st_point(c(149, 55)), #right, top
  crs = target_crs #the EPSG identifier of WGS84 (used in GPS)
)

window_coord_sf <- window_coord %>%
  st_transform(crs = target_crs) %>%
  st_coordinates() # retrieve coordinates

# Missions Locations -----------------------------------------------------------

ValueEmbassies <- DisplayMap (world, target_crs, window_coord_sf, MapCountriesWithSwissEmbassy, SwissAsianMissionsLocationsGeo, MapCountriesWithSwissEmbassy[[ys_Ambassade]],"Asia Pacific", "Swiss Embassies", "BCN" )

ValueEmbassies

# Diplomatic accreditations ----------------------------------------------------

ValueRepresentations <- DisplayMap (world, target_crs, window_coord_sf, MapCountriesWithSwissRepresentation,Pays_Ambassade,  SwissAsianMissionsLocationsGeo, "Asia Pacific", "Swiss Embassies", "BCN" )

ValueRepresentations

# DA accreditations ------------------------------------------------------------

cols <- c("none" = "grey", "TRUE" = "darkblue", "FALSE" = "lightblue")

ValueDA <- DisplayMap (world, target_crs, window_coord_sf, MapCountriesWithSwissDA, SwissAsianDALocationsGeo, AD_origine, "Asia Pacific", "Swiss DA and Accreditated States", "BCN" )

ValueDA
```


